create table "public"."game_audience" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."game_audience" enable row level security;

alter table "public"."game" add column "game_audience_id" smallint;

CREATE UNIQUE INDEX game_audience_type_name_key ON public.game_audience USING btree (name);

CREATE UNIQUE INDEX game_audience_type_pkey ON public.game_audience USING btree (id);

alter table "public"."game_audience" add constraint "game_audience_type_pkey" PRIMARY KEY using index "game_audience_type_pkey";

alter table "public"."game" add constraint "public_game_game_audience_id_fkey" FOREIGN KEY (game_audience_id) REFERENCES game_audience(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."game" validate constraint "public_game_game_audience_id_fkey";

alter table "public"."game_audience" add constraint "game_audience_type_name_key" UNIQUE using index "game_audience_type_name_key";

grant delete on table "public"."game_audience" to "anon";

grant insert on table "public"."game_audience" to "anon";

grant references on table "public"."game_audience" to "anon";

grant select on table "public"."game_audience" to "anon";

grant trigger on table "public"."game_audience" to "anon";

grant truncate on table "public"."game_audience" to "anon";

grant update on table "public"."game_audience" to "anon";

grant delete on table "public"."game_audience" to "authenticated";

grant insert on table "public"."game_audience" to "authenticated";

grant references on table "public"."game_audience" to "authenticated";

grant select on table "public"."game_audience" to "authenticated";

grant trigger on table "public"."game_audience" to "authenticated";

grant truncate on table "public"."game_audience" to "authenticated";

grant update on table "public"."game_audience" to "authenticated";

grant delete on table "public"."game_audience" to "service_role";

grant insert on table "public"."game_audience" to "service_role";

grant references on table "public"."game_audience" to "service_role";

grant select on table "public"."game_audience" to "service_role";

grant trigger on table "public"."game_audience" to "service_role";

grant truncate on table "public"."game_audience" to "service_role";

grant update on table "public"."game_audience" to "service_role";


