create table "public"."game_category" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."game_category" enable row level security;

alter table "public"."game" add column "game_category_id" smallint not null;

CREATE UNIQUE INDEX game_category_name_key ON public.game_category USING btree (name);

CREATE UNIQUE INDEX game_category_pkey ON public.game_category USING btree (id);

alter table "public"."game_category" add constraint "game_category_pkey" PRIMARY KEY using index "game_category_pkey";

alter table "public"."game" add constraint "public_game_game_category_id_fkey" FOREIGN KEY (game_category_id) REFERENCES game_category(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."game" validate constraint "public_game_game_category_id_fkey";

alter table "public"."game_category" add constraint "game_category_name_key" UNIQUE using index "game_category_name_key";

grant delete on table "public"."game_category" to "anon";

grant insert on table "public"."game_category" to "anon";

grant references on table "public"."game_category" to "anon";

grant select on table "public"."game_category" to "anon";

grant trigger on table "public"."game_category" to "anon";

grant truncate on table "public"."game_category" to "anon";

grant update on table "public"."game_category" to "anon";

grant delete on table "public"."game_category" to "authenticated";

grant insert on table "public"."game_category" to "authenticated";

grant references on table "public"."game_category" to "authenticated";

grant select on table "public"."game_category" to "authenticated";

grant trigger on table "public"."game_category" to "authenticated";

grant truncate on table "public"."game_category" to "authenticated";

grant update on table "public"."game_category" to "authenticated";

grant delete on table "public"."game_category" to "service_role";

grant insert on table "public"."game_category" to "service_role";

grant references on table "public"."game_category" to "service_role";

grant select on table "public"."game_category" to "service_role";

grant trigger on table "public"."game_category" to "service_role";

grant truncate on table "public"."game_category" to "service_role";

grant update on table "public"."game_category" to "service_role";


