alter table "public"."game" drop constraint "public_game_game_type_id_fkey";

create table "public"."game_has_game_type" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "game_type_id" smallint not null
);


alter table "public"."game_has_game_type" enable row level security;

alter table "public"."game" drop column "game_type_id";

CREATE UNIQUE INDEX game_has_game_type_pkey ON public.game_has_game_type USING btree (id);

alter table "public"."game_has_game_type" add constraint "game_has_game_type_pkey" PRIMARY KEY using index "game_has_game_type_pkey";

alter table "public"."game_has_game_type" add constraint "public_game_has_game_type_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."game_has_game_type" validate constraint "public_game_has_game_type_game_id_fkey";

alter table "public"."game_has_game_type" add constraint "public_game_has_game_type_game_type_id_fkey" FOREIGN KEY (game_type_id) REFERENCES game_type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."game_has_game_type" validate constraint "public_game_has_game_type_game_type_id_fkey";

grant delete on table "public"."game_has_game_type" to "anon";

grant insert on table "public"."game_has_game_type" to "anon";

grant references on table "public"."game_has_game_type" to "anon";

grant select on table "public"."game_has_game_type" to "anon";

grant trigger on table "public"."game_has_game_type" to "anon";

grant truncate on table "public"."game_has_game_type" to "anon";

grant update on table "public"."game_has_game_type" to "anon";

grant delete on table "public"."game_has_game_type" to "authenticated";

grant insert on table "public"."game_has_game_type" to "authenticated";

grant references on table "public"."game_has_game_type" to "authenticated";

grant select on table "public"."game_has_game_type" to "authenticated";

grant trigger on table "public"."game_has_game_type" to "authenticated";

grant truncate on table "public"."game_has_game_type" to "authenticated";

grant update on table "public"."game_has_game_type" to "authenticated";

grant delete on table "public"."game_has_game_type" to "service_role";

grant insert on table "public"."game_has_game_type" to "service_role";

grant references on table "public"."game_has_game_type" to "service_role";

grant select on table "public"."game_has_game_type" to "service_role";

grant trigger on table "public"."game_has_game_type" to "service_role";

grant truncate on table "public"."game_has_game_type" to "service_role";

grant update on table "public"."game_has_game_type" to "service_role";


