alter table "public"."game" drop constraint "game_name_unique";

drop index if exists "public"."game_name_unique";

create table "public"."action_card_settings_translation" (
    "id" integer generated by default as identity not null,
    "action_card_settings_id" integer not null,
    "language" character varying not null default 'en'::character varying,
    "prompt" text not null
);


alter table "public"."action_card_settings_translation" enable row level security;

create table "public"."action_card_translation" (
    "id" bigint generated by default as identity not null,
    "action_card_id" bigint not null,
    "language" character varying not null default 'en'::character varying,
    "value" text not null
);


alter table "public"."action_card_translation" enable row level security;

create table "public"."game_translation" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "language" character varying not null default 'en'::character varying,
    "name" character varying not null,
    "intro_description" text,
    "descriptions" text[] not null,
    "custom_end_game_sentence" text not null
);


alter table "public"."game_translation" enable row level security;

alter table "public"."accessory" add column "created_at" timestamp with time zone not null default now();

alter table "public"."action_card" drop column "value";

alter table "public"."action_card" add column "created_at" timestamp with time zone not null default now();

alter table "public"."action_card_settings" drop column "prompt";

alter table "public"."action_card_settings" add column "created_at" timestamp with time zone not null default now();

alter table "public"."game" drop column "custom_end_game_sentence";

alter table "public"."game" drop column "descriptions";

alter table "public"."game" drop column "intro_description";

alter table "public"."game" drop column "name";

alter table "public"."game_type" add column "created_at" timestamp with time zone not null default now();

CREATE UNIQUE INDEX action_card_settings_translation_pkey ON public.action_card_settings_translation USING btree (id);

CREATE UNIQUE INDEX action_card_translation_pkey ON public.action_card_translation USING btree (id);

CREATE UNIQUE INDEX game_translation_name_key ON public.game_translation USING btree (name);

CREATE UNIQUE INDEX game_translation_pkey ON public.game_translation USING btree (id);

alter table "public"."action_card_settings_translation" add constraint "action_card_settings_translation_pkey" PRIMARY KEY using index "action_card_settings_translation_pkey";

alter table "public"."action_card_translation" add constraint "action_card_translation_pkey" PRIMARY KEY using index "action_card_translation_pkey";

alter table "public"."game_translation" add constraint "game_translation_pkey" PRIMARY KEY using index "game_translation_pkey";

alter table "public"."action_card_settings_translation" add constraint "public_action_card_settings_translation_action_card_settings_id" FOREIGN KEY (action_card_settings_id) REFERENCES action_card_settings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."action_card_settings_translation" validate constraint "public_action_card_settings_translation_action_card_settings_id";

alter table "public"."action_card_translation" add constraint "public_action_card_translation_action_card_id_fkey" FOREIGN KEY (action_card_id) REFERENCES action_card(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."action_card_translation" validate constraint "public_action_card_translation_action_card_id_fkey";

alter table "public"."game_translation" add constraint "game_translation_name_key" UNIQUE using index "game_translation_name_key";

alter table "public"."game_translation" add constraint "public_game_translation_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."game_translation" validate constraint "public_game_translation_game_id_fkey";

grant delete on table "public"."action_card_settings_translation" to "anon";

grant insert on table "public"."action_card_settings_translation" to "anon";

grant references on table "public"."action_card_settings_translation" to "anon";

grant select on table "public"."action_card_settings_translation" to "anon";

grant trigger on table "public"."action_card_settings_translation" to "anon";

grant truncate on table "public"."action_card_settings_translation" to "anon";

grant update on table "public"."action_card_settings_translation" to "anon";

grant delete on table "public"."action_card_settings_translation" to "authenticated";

grant insert on table "public"."action_card_settings_translation" to "authenticated";

grant references on table "public"."action_card_settings_translation" to "authenticated";

grant select on table "public"."action_card_settings_translation" to "authenticated";

grant trigger on table "public"."action_card_settings_translation" to "authenticated";

grant truncate on table "public"."action_card_settings_translation" to "authenticated";

grant update on table "public"."action_card_settings_translation" to "authenticated";

grant delete on table "public"."action_card_settings_translation" to "service_role";

grant insert on table "public"."action_card_settings_translation" to "service_role";

grant references on table "public"."action_card_settings_translation" to "service_role";

grant select on table "public"."action_card_settings_translation" to "service_role";

grant trigger on table "public"."action_card_settings_translation" to "service_role";

grant truncate on table "public"."action_card_settings_translation" to "service_role";

grant update on table "public"."action_card_settings_translation" to "service_role";

grant delete on table "public"."action_card_translation" to "anon";

grant insert on table "public"."action_card_translation" to "anon";

grant references on table "public"."action_card_translation" to "anon";

grant select on table "public"."action_card_translation" to "anon";

grant trigger on table "public"."action_card_translation" to "anon";

grant truncate on table "public"."action_card_translation" to "anon";

grant update on table "public"."action_card_translation" to "anon";

grant delete on table "public"."action_card_translation" to "authenticated";

grant insert on table "public"."action_card_translation" to "authenticated";

grant references on table "public"."action_card_translation" to "authenticated";

grant select on table "public"."action_card_translation" to "authenticated";

grant trigger on table "public"."action_card_translation" to "authenticated";

grant truncate on table "public"."action_card_translation" to "authenticated";

grant update on table "public"."action_card_translation" to "authenticated";

grant delete on table "public"."action_card_translation" to "service_role";

grant insert on table "public"."action_card_translation" to "service_role";

grant references on table "public"."action_card_translation" to "service_role";

grant select on table "public"."action_card_translation" to "service_role";

grant trigger on table "public"."action_card_translation" to "service_role";

grant truncate on table "public"."action_card_translation" to "service_role";

grant update on table "public"."action_card_translation" to "service_role";

grant delete on table "public"."game_translation" to "anon";

grant insert on table "public"."game_translation" to "anon";

grant references on table "public"."game_translation" to "anon";

grant select on table "public"."game_translation" to "anon";

grant trigger on table "public"."game_translation" to "anon";

grant truncate on table "public"."game_translation" to "anon";

grant update on table "public"."game_translation" to "anon";

grant delete on table "public"."game_translation" to "authenticated";

grant insert on table "public"."game_translation" to "authenticated";

grant references on table "public"."game_translation" to "authenticated";

grant select on table "public"."game_translation" to "authenticated";

grant trigger on table "public"."game_translation" to "authenticated";

grant truncate on table "public"."game_translation" to "authenticated";

grant update on table "public"."game_translation" to "authenticated";

grant delete on table "public"."game_translation" to "service_role";

grant insert on table "public"."game_translation" to "service_role";

grant references on table "public"."game_translation" to "service_role";

grant select on table "public"."game_translation" to "service_role";

grant trigger on table "public"."game_translation" to "service_role";

grant truncate on table "public"."game_translation" to "service_role";

grant update on table "public"."game_translation" to "service_role";


