create table "public"."action_card" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."action_card" enable row level security;

create table "public"."action_card_content_type" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."action_card_content_type" enable row level security;

create table "public"."action_card_settings" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "state_id" smallint not null,
    "content_type_id" smallint not null,
    "card_limit" smallint,
    "card_seconds" smallint,
    "is_auto_next" boolean,
    "is_player_creative" boolean,
    "prompt" character varying
);


alter table "public"."action_card_settings" enable row level security;

create table "public"."action_card_settings_has_action_card" (
    "id" bigint generated by default as identity not null,
    "action_card_settings_id" integer not null,
    "action_card_id" bigint not null
);


alter table "public"."action_card_settings_has_action_card" enable row level security;

create table "public"."action_card_state" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."action_card_state" enable row level security;

CREATE UNIQUE INDEX action_card_content_type_name_key ON public.action_card_content_type USING btree (name);

CREATE UNIQUE INDEX action_card_content_type_pkey ON public.action_card_content_type USING btree (id);

CREATE UNIQUE INDEX action_card_pkey ON public.action_card USING btree (id);

CREATE UNIQUE INDEX action_card_settings_has_action_card_pkey ON public.action_card_settings_has_action_card USING btree (id);

CREATE UNIQUE INDEX action_card_settings_pkey ON public.action_card_settings USING btree (id);

CREATE UNIQUE INDEX action_card_state_name_key ON public.action_card_state USING btree (name);

CREATE UNIQUE INDEX action_card_state_pkey ON public.action_card_state USING btree (id);

alter table "public"."action_card" add constraint "action_card_pkey" PRIMARY KEY using index "action_card_pkey";

alter table "public"."action_card_content_type" add constraint "action_card_content_type_pkey" PRIMARY KEY using index "action_card_content_type_pkey";

alter table "public"."action_card_settings" add constraint "action_card_settings_pkey" PRIMARY KEY using index "action_card_settings_pkey";

alter table "public"."action_card_settings_has_action_card" add constraint "action_card_settings_has_action_card_pkey" PRIMARY KEY using index "action_card_settings_has_action_card_pkey";

alter table "public"."action_card_state" add constraint "action_card_state_pkey" PRIMARY KEY using index "action_card_state_pkey";

alter table "public"."action_card_content_type" add constraint "action_card_content_type_name_key" UNIQUE using index "action_card_content_type_name_key";

alter table "public"."action_card_settings" add constraint "public_action_card_settings_content_type_id_fkey" FOREIGN KEY (content_type_id) REFERENCES action_card_content_type(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."action_card_settings" validate constraint "public_action_card_settings_content_type_id_fkey";

alter table "public"."action_card_settings" add constraint "public_action_card_settings_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."action_card_settings" validate constraint "public_action_card_settings_game_id_fkey";

alter table "public"."action_card_settings" add constraint "public_action_card_settings_state_id_fkey" FOREIGN KEY (state_id) REFERENCES action_card_state(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."action_card_settings" validate constraint "public_action_card_settings_state_id_fkey";

alter table "public"."action_card_settings_has_action_card" add constraint "public_action_card_settings_has_action_card_action_card_id_fkey" FOREIGN KEY (action_card_id) REFERENCES action_card(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."action_card_settings_has_action_card" validate constraint "public_action_card_settings_has_action_card_action_card_id_fkey";

alter table "public"."action_card_settings_has_action_card" add constraint "public_action_card_settings_has_action_card_action_card_setting" FOREIGN KEY (action_card_settings_id) REFERENCES action_card_settings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."action_card_settings_has_action_card" validate constraint "public_action_card_settings_has_action_card_action_card_setting";

alter table "public"."action_card_state" add constraint "action_card_state_name_key" UNIQUE using index "action_card_state_name_key";

grant delete on table "public"."action_card" to "anon";

grant insert on table "public"."action_card" to "anon";

grant references on table "public"."action_card" to "anon";

grant select on table "public"."action_card" to "anon";

grant trigger on table "public"."action_card" to "anon";

grant truncate on table "public"."action_card" to "anon";

grant update on table "public"."action_card" to "anon";

grant delete on table "public"."action_card" to "authenticated";

grant insert on table "public"."action_card" to "authenticated";

grant references on table "public"."action_card" to "authenticated";

grant select on table "public"."action_card" to "authenticated";

grant trigger on table "public"."action_card" to "authenticated";

grant truncate on table "public"."action_card" to "authenticated";

grant update on table "public"."action_card" to "authenticated";

grant delete on table "public"."action_card" to "service_role";

grant insert on table "public"."action_card" to "service_role";

grant references on table "public"."action_card" to "service_role";

grant select on table "public"."action_card" to "service_role";

grant trigger on table "public"."action_card" to "service_role";

grant truncate on table "public"."action_card" to "service_role";

grant update on table "public"."action_card" to "service_role";

grant delete on table "public"."action_card_content_type" to "anon";

grant insert on table "public"."action_card_content_type" to "anon";

grant references on table "public"."action_card_content_type" to "anon";

grant select on table "public"."action_card_content_type" to "anon";

grant trigger on table "public"."action_card_content_type" to "anon";

grant truncate on table "public"."action_card_content_type" to "anon";

grant update on table "public"."action_card_content_type" to "anon";

grant delete on table "public"."action_card_content_type" to "authenticated";

grant insert on table "public"."action_card_content_type" to "authenticated";

grant references on table "public"."action_card_content_type" to "authenticated";

grant select on table "public"."action_card_content_type" to "authenticated";

grant trigger on table "public"."action_card_content_type" to "authenticated";

grant truncate on table "public"."action_card_content_type" to "authenticated";

grant update on table "public"."action_card_content_type" to "authenticated";

grant delete on table "public"."action_card_content_type" to "service_role";

grant insert on table "public"."action_card_content_type" to "service_role";

grant references on table "public"."action_card_content_type" to "service_role";

grant select on table "public"."action_card_content_type" to "service_role";

grant trigger on table "public"."action_card_content_type" to "service_role";

grant truncate on table "public"."action_card_content_type" to "service_role";

grant update on table "public"."action_card_content_type" to "service_role";

grant delete on table "public"."action_card_settings" to "anon";

grant insert on table "public"."action_card_settings" to "anon";

grant references on table "public"."action_card_settings" to "anon";

grant select on table "public"."action_card_settings" to "anon";

grant trigger on table "public"."action_card_settings" to "anon";

grant truncate on table "public"."action_card_settings" to "anon";

grant update on table "public"."action_card_settings" to "anon";

grant delete on table "public"."action_card_settings" to "authenticated";

grant insert on table "public"."action_card_settings" to "authenticated";

grant references on table "public"."action_card_settings" to "authenticated";

grant select on table "public"."action_card_settings" to "authenticated";

grant trigger on table "public"."action_card_settings" to "authenticated";

grant truncate on table "public"."action_card_settings" to "authenticated";

grant update on table "public"."action_card_settings" to "authenticated";

grant delete on table "public"."action_card_settings" to "service_role";

grant insert on table "public"."action_card_settings" to "service_role";

grant references on table "public"."action_card_settings" to "service_role";

grant select on table "public"."action_card_settings" to "service_role";

grant trigger on table "public"."action_card_settings" to "service_role";

grant truncate on table "public"."action_card_settings" to "service_role";

grant update on table "public"."action_card_settings" to "service_role";

grant delete on table "public"."action_card_settings_has_action_card" to "anon";

grant insert on table "public"."action_card_settings_has_action_card" to "anon";

grant references on table "public"."action_card_settings_has_action_card" to "anon";

grant select on table "public"."action_card_settings_has_action_card" to "anon";

grant trigger on table "public"."action_card_settings_has_action_card" to "anon";

grant truncate on table "public"."action_card_settings_has_action_card" to "anon";

grant update on table "public"."action_card_settings_has_action_card" to "anon";

grant delete on table "public"."action_card_settings_has_action_card" to "authenticated";

grant insert on table "public"."action_card_settings_has_action_card" to "authenticated";

grant references on table "public"."action_card_settings_has_action_card" to "authenticated";

grant select on table "public"."action_card_settings_has_action_card" to "authenticated";

grant trigger on table "public"."action_card_settings_has_action_card" to "authenticated";

grant truncate on table "public"."action_card_settings_has_action_card" to "authenticated";

grant update on table "public"."action_card_settings_has_action_card" to "authenticated";

grant delete on table "public"."action_card_settings_has_action_card" to "service_role";

grant insert on table "public"."action_card_settings_has_action_card" to "service_role";

grant references on table "public"."action_card_settings_has_action_card" to "service_role";

grant select on table "public"."action_card_settings_has_action_card" to "service_role";

grant trigger on table "public"."action_card_settings_has_action_card" to "service_role";

grant truncate on table "public"."action_card_settings_has_action_card" to "service_role";

grant update on table "public"."action_card_settings_has_action_card" to "service_role";

grant delete on table "public"."action_card_state" to "anon";

grant insert on table "public"."action_card_state" to "anon";

grant references on table "public"."action_card_state" to "anon";

grant select on table "public"."action_card_state" to "anon";

grant trigger on table "public"."action_card_state" to "anon";

grant truncate on table "public"."action_card_state" to "anon";

grant update on table "public"."action_card_state" to "anon";

grant delete on table "public"."action_card_state" to "authenticated";

grant insert on table "public"."action_card_state" to "authenticated";

grant references on table "public"."action_card_state" to "authenticated";

grant select on table "public"."action_card_state" to "authenticated";

grant trigger on table "public"."action_card_state" to "authenticated";

grant truncate on table "public"."action_card_state" to "authenticated";

grant update on table "public"."action_card_state" to "authenticated";

grant delete on table "public"."action_card_state" to "service_role";

grant insert on table "public"."action_card_state" to "service_role";

grant references on table "public"."action_card_state" to "service_role";

grant select on table "public"."action_card_state" to "service_role";

grant trigger on table "public"."action_card_state" to "service_role";

grant truncate on table "public"."action_card_state" to "service_role";

grant update on table "public"."action_card_state" to "service_role";


