create table "public"."accessory" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."accessory" enable row level security;

create table "public"."challenge" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" text not null
);


alter table "public"."challenge" enable row level security;

create table "public"."game" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "messages" text[] not null,
    "min_players" smallint not null default '2'::smallint,
    "max_players" smallint,
    "activity_level" smallint,
    "alcohol_level" smallint,
    "minutes" smallint,
    "game_type_id" smallint not null,
    "player_group_type_id" smallint
);


alter table "public"."game" enable row level security;

create table "public"."game_has_accessory" (
    "id" integer generated by default as identity not null,
    "game_id" integer not null,
    "accessory_id" smallint not null
);


alter table "public"."game_has_accessory" enable row level security;

create table "public"."game_type" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."game_type" enable row level security;

create table "public"."player" (
    "id" uuid not null default gen_random_uuid(),
    "username" character varying not null,
    "first_name" character varying,
    "last_name" character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "is_guest" boolean not null default true,
    "deleted_at" timestamp with time zone
);


alter table "public"."player" enable row level security;

create table "public"."player_group_type" (
    "id" smallint generated by default as identity not null,
    "name" character varying not null
);


alter table "public"."player_group_type" enable row level security;

create table "public"."player_has_room" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "is_host" boolean not null default false,
    "room_id" text not null,
    "player_id" uuid not null
);


alter table "public"."player_has_room" enable row level security;

create table "public"."room" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "max_players" smallint not null
);


alter table "public"."room" enable row level security;

CREATE UNIQUE INDEX accessory_pkey ON public.accessory USING btree (id);

CREATE UNIQUE INDEX challenge_pkey ON public.challenge USING btree (id);

CREATE UNIQUE INDEX game_has_accessory_pkey ON public.game_has_accessory USING btree (id);

CREATE UNIQUE INDEX game_pkey ON public.game USING btree (id);

CREATE UNIQUE INDEX game_type_pkey ON public.game_type USING btree (id);

CREATE UNIQUE INDEX player_has_room_pkey ON public.player_has_room USING btree (id);

CREATE UNIQUE INDEX player_pkey ON public.player USING btree (id);

CREATE UNIQUE INDEX player_type_pkey ON public.player_group_type USING btree (id);

CREATE UNIQUE INDEX player_username_key ON public.player USING btree (username);

CREATE UNIQUE INDEX room_pkey ON public.room USING btree (id);

alter table "public"."accessory" add constraint "accessory_pkey" PRIMARY KEY using index "accessory_pkey";

alter table "public"."challenge" add constraint "challenge_pkey" PRIMARY KEY using index "challenge_pkey";

alter table "public"."game" add constraint "game_pkey" PRIMARY KEY using index "game_pkey";

alter table "public"."game_has_accessory" add constraint "game_has_accessory_pkey" PRIMARY KEY using index "game_has_accessory_pkey";

alter table "public"."game_type" add constraint "game_type_pkey" PRIMARY KEY using index "game_type_pkey";

alter table "public"."player" add constraint "player_pkey" PRIMARY KEY using index "player_pkey";

alter table "public"."player_group_type" add constraint "player_type_pkey" PRIMARY KEY using index "player_type_pkey";

alter table "public"."player_has_room" add constraint "player_has_room_pkey" PRIMARY KEY using index "player_has_room_pkey";

alter table "public"."room" add constraint "room_pkey" PRIMARY KEY using index "room_pkey";

alter table "public"."game" add constraint "public_game_game_type_id_fkey" FOREIGN KEY (game_type_id) REFERENCES game_type(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."game" validate constraint "public_game_game_type_id_fkey";

alter table "public"."game" add constraint "public_game_player_group_type_id_fkey" FOREIGN KEY (player_group_type_id) REFERENCES player_group_type(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."game" validate constraint "public_game_player_group_type_id_fkey";

alter table "public"."game_has_accessory" add constraint "public_game_has_accessory_accessory_id_fkey" FOREIGN KEY (accessory_id) REFERENCES accessory(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."game_has_accessory" validate constraint "public_game_has_accessory_accessory_id_fkey";

alter table "public"."game_has_accessory" add constraint "public_game_has_accessory_game_id_fkey" FOREIGN KEY (game_id) REFERENCES game(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."game_has_accessory" validate constraint "public_game_has_accessory_game_id_fkey";

alter table "public"."player" add constraint "player_username_key" UNIQUE using index "player_username_key";

alter table "public"."player_has_room" add constraint "public_player_has_room_player_id_fkey" FOREIGN KEY (player_id) REFERENCES player(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."player_has_room" validate constraint "public_player_has_room_player_id_fkey";

alter table "public"."player_has_room" add constraint "public_player_has_room_room_id_fkey" FOREIGN KEY (room_id) REFERENCES room(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."player_has_room" validate constraint "public_player_has_room_room_id_fkey";

create or replace view "public"."random_challenge" as  SELECT challenge.id,
    challenge.created_at,
    challenge.message
   FROM challenge
  ORDER BY (random());


grant delete on table "public"."accessory" to "anon";

grant insert on table "public"."accessory" to "anon";

grant references on table "public"."accessory" to "anon";

grant select on table "public"."accessory" to "anon";

grant trigger on table "public"."accessory" to "anon";

grant truncate on table "public"."accessory" to "anon";

grant update on table "public"."accessory" to "anon";

grant delete on table "public"."accessory" to "authenticated";

grant insert on table "public"."accessory" to "authenticated";

grant references on table "public"."accessory" to "authenticated";

grant select on table "public"."accessory" to "authenticated";

grant trigger on table "public"."accessory" to "authenticated";

grant truncate on table "public"."accessory" to "authenticated";

grant update on table "public"."accessory" to "authenticated";

grant delete on table "public"."accessory" to "service_role";

grant insert on table "public"."accessory" to "service_role";

grant references on table "public"."accessory" to "service_role";

grant select on table "public"."accessory" to "service_role";

grant trigger on table "public"."accessory" to "service_role";

grant truncate on table "public"."accessory" to "service_role";

grant update on table "public"."accessory" to "service_role";

grant delete on table "public"."challenge" to "anon";

grant insert on table "public"."challenge" to "anon";

grant references on table "public"."challenge" to "anon";

grant select on table "public"."challenge" to "anon";

grant trigger on table "public"."challenge" to "anon";

grant truncate on table "public"."challenge" to "anon";

grant update on table "public"."challenge" to "anon";

grant delete on table "public"."challenge" to "authenticated";

grant insert on table "public"."challenge" to "authenticated";

grant references on table "public"."challenge" to "authenticated";

grant select on table "public"."challenge" to "authenticated";

grant trigger on table "public"."challenge" to "authenticated";

grant truncate on table "public"."challenge" to "authenticated";

grant update on table "public"."challenge" to "authenticated";

grant delete on table "public"."challenge" to "service_role";

grant insert on table "public"."challenge" to "service_role";

grant references on table "public"."challenge" to "service_role";

grant select on table "public"."challenge" to "service_role";

grant trigger on table "public"."challenge" to "service_role";

grant truncate on table "public"."challenge" to "service_role";

grant update on table "public"."challenge" to "service_role";

grant delete on table "public"."game" to "anon";

grant insert on table "public"."game" to "anon";

grant references on table "public"."game" to "anon";

grant select on table "public"."game" to "anon";

grant trigger on table "public"."game" to "anon";

grant truncate on table "public"."game" to "anon";

grant update on table "public"."game" to "anon";

grant delete on table "public"."game" to "authenticated";

grant insert on table "public"."game" to "authenticated";

grant references on table "public"."game" to "authenticated";

grant select on table "public"."game" to "authenticated";

grant trigger on table "public"."game" to "authenticated";

grant truncate on table "public"."game" to "authenticated";

grant update on table "public"."game" to "authenticated";

grant delete on table "public"."game" to "service_role";

grant insert on table "public"."game" to "service_role";

grant references on table "public"."game" to "service_role";

grant select on table "public"."game" to "service_role";

grant trigger on table "public"."game" to "service_role";

grant truncate on table "public"."game" to "service_role";

grant update on table "public"."game" to "service_role";

grant delete on table "public"."game_has_accessory" to "anon";

grant insert on table "public"."game_has_accessory" to "anon";

grant references on table "public"."game_has_accessory" to "anon";

grant select on table "public"."game_has_accessory" to "anon";

grant trigger on table "public"."game_has_accessory" to "anon";

grant truncate on table "public"."game_has_accessory" to "anon";

grant update on table "public"."game_has_accessory" to "anon";

grant delete on table "public"."game_has_accessory" to "authenticated";

grant insert on table "public"."game_has_accessory" to "authenticated";

grant references on table "public"."game_has_accessory" to "authenticated";

grant select on table "public"."game_has_accessory" to "authenticated";

grant trigger on table "public"."game_has_accessory" to "authenticated";

grant truncate on table "public"."game_has_accessory" to "authenticated";

grant update on table "public"."game_has_accessory" to "authenticated";

grant delete on table "public"."game_has_accessory" to "service_role";

grant insert on table "public"."game_has_accessory" to "service_role";

grant references on table "public"."game_has_accessory" to "service_role";

grant select on table "public"."game_has_accessory" to "service_role";

grant trigger on table "public"."game_has_accessory" to "service_role";

grant truncate on table "public"."game_has_accessory" to "service_role";

grant update on table "public"."game_has_accessory" to "service_role";

grant delete on table "public"."game_type" to "anon";

grant insert on table "public"."game_type" to "anon";

grant references on table "public"."game_type" to "anon";

grant select on table "public"."game_type" to "anon";

grant trigger on table "public"."game_type" to "anon";

grant truncate on table "public"."game_type" to "anon";

grant update on table "public"."game_type" to "anon";

grant delete on table "public"."game_type" to "authenticated";

grant insert on table "public"."game_type" to "authenticated";

grant references on table "public"."game_type" to "authenticated";

grant select on table "public"."game_type" to "authenticated";

grant trigger on table "public"."game_type" to "authenticated";

grant truncate on table "public"."game_type" to "authenticated";

grant update on table "public"."game_type" to "authenticated";

grant delete on table "public"."game_type" to "service_role";

grant insert on table "public"."game_type" to "service_role";

grant references on table "public"."game_type" to "service_role";

grant select on table "public"."game_type" to "service_role";

grant trigger on table "public"."game_type" to "service_role";

grant truncate on table "public"."game_type" to "service_role";

grant update on table "public"."game_type" to "service_role";

grant delete on table "public"."player" to "anon";

grant insert on table "public"."player" to "anon";

grant references on table "public"."player" to "anon";

grant select on table "public"."player" to "anon";

grant trigger on table "public"."player" to "anon";

grant truncate on table "public"."player" to "anon";

grant update on table "public"."player" to "anon";

grant delete on table "public"."player" to "authenticated";

grant insert on table "public"."player" to "authenticated";

grant references on table "public"."player" to "authenticated";

grant select on table "public"."player" to "authenticated";

grant trigger on table "public"."player" to "authenticated";

grant truncate on table "public"."player" to "authenticated";

grant update on table "public"."player" to "authenticated";

grant delete on table "public"."player" to "service_role";

grant insert on table "public"."player" to "service_role";

grant references on table "public"."player" to "service_role";

grant select on table "public"."player" to "service_role";

grant trigger on table "public"."player" to "service_role";

grant truncate on table "public"."player" to "service_role";

grant update on table "public"."player" to "service_role";

grant delete on table "public"."player_group_type" to "anon";

grant insert on table "public"."player_group_type" to "anon";

grant references on table "public"."player_group_type" to "anon";

grant select on table "public"."player_group_type" to "anon";

grant trigger on table "public"."player_group_type" to "anon";

grant truncate on table "public"."player_group_type" to "anon";

grant update on table "public"."player_group_type" to "anon";

grant delete on table "public"."player_group_type" to "authenticated";

grant insert on table "public"."player_group_type" to "authenticated";

grant references on table "public"."player_group_type" to "authenticated";

grant select on table "public"."player_group_type" to "authenticated";

grant trigger on table "public"."player_group_type" to "authenticated";

grant truncate on table "public"."player_group_type" to "authenticated";

grant update on table "public"."player_group_type" to "authenticated";

grant delete on table "public"."player_group_type" to "service_role";

grant insert on table "public"."player_group_type" to "service_role";

grant references on table "public"."player_group_type" to "service_role";

grant select on table "public"."player_group_type" to "service_role";

grant trigger on table "public"."player_group_type" to "service_role";

grant truncate on table "public"."player_group_type" to "service_role";

grant update on table "public"."player_group_type" to "service_role";

grant delete on table "public"."player_has_room" to "anon";

grant insert on table "public"."player_has_room" to "anon";

grant references on table "public"."player_has_room" to "anon";

grant select on table "public"."player_has_room" to "anon";

grant trigger on table "public"."player_has_room" to "anon";

grant truncate on table "public"."player_has_room" to "anon";

grant update on table "public"."player_has_room" to "anon";

grant delete on table "public"."player_has_room" to "authenticated";

grant insert on table "public"."player_has_room" to "authenticated";

grant references on table "public"."player_has_room" to "authenticated";

grant select on table "public"."player_has_room" to "authenticated";

grant trigger on table "public"."player_has_room" to "authenticated";

grant truncate on table "public"."player_has_room" to "authenticated";

grant update on table "public"."player_has_room" to "authenticated";

grant delete on table "public"."player_has_room" to "service_role";

grant insert on table "public"."player_has_room" to "service_role";

grant references on table "public"."player_has_room" to "service_role";

grant select on table "public"."player_has_room" to "service_role";

grant trigger on table "public"."player_has_room" to "service_role";

grant truncate on table "public"."player_has_room" to "service_role";

grant update on table "public"."player_has_room" to "service_role";

grant delete on table "public"."room" to "anon";

grant insert on table "public"."room" to "anon";

grant references on table "public"."room" to "anon";

grant select on table "public"."room" to "anon";

grant trigger on table "public"."room" to "anon";

grant truncate on table "public"."room" to "anon";

grant update on table "public"."room" to "anon";

grant delete on table "public"."room" to "authenticated";

grant insert on table "public"."room" to "authenticated";

grant references on table "public"."room" to "authenticated";

grant select on table "public"."room" to "authenticated";

grant trigger on table "public"."room" to "authenticated";

grant truncate on table "public"."room" to "authenticated";

grant update on table "public"."room" to "authenticated";

grant delete on table "public"."room" to "service_role";

grant insert on table "public"."room" to "service_role";

grant references on table "public"."room" to "service_role";

grant select on table "public"."room" to "service_role";

grant trigger on table "public"."room" to "service_role";

grant truncate on table "public"."room" to "service_role";

grant update on table "public"."room" to "service_role";

create policy "Enable read access for all users"
on "public"."challenge"
as permissive
for select
to public
using (true);



