name: Deno Test Coverage

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    if: github.event.pull_request.merged == true # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Function Files
        run: deno cache supabase/functions/**/index.ts

      - name: Run Tests with Coverage
        run: |
          deno test --coverage=coverage
          deno coverage coverage --lcov > coverage/lcov.info

      - name: Upload coverage to Coveralls
        run: |
          deno install -qA --unstable https://deno.land/x/cov@v0.1.0/cli.ts
          cat coverage/lcov.info | deno run -A --unstable https://deno.land/x/cov@v0.1.0/upload.ts --repo-token ${{ secrets.COVERALLS_REPO_TOKEN }}
